// <auto-generated />
using System.Collections.Generic;
using BugILikePostgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BugILikePostgres.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20201102101449_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("BugILikePostgres.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<List<string>>("Topics")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Topics");

                    b.ToTable("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
